/**
 * BlockData API
 * BlockData API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class BlockConfig {
    /**
    * id
    */
    'id'?: string;
    /**
    * 应用ID
    */
    'appId'?: string;
    /**
    * 名称
    */
    'name'?: string;
    /**
    * 渲染数据
    */
    'renderData'?: object;
    /**
    * 编辑数据
    */
    'editorData'?: object;
    /**
    * 创建时间
    */
    'ctime'?: number;
    /**
    * 更改时间
    */
    'mtime'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "appId",
            "baseName": "appId",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "renderData",
            "baseName": "renderData",
            "type": "object"
        },
        {
            "name": "editorData",
            "baseName": "editorData",
            "type": "object"
        },
        {
            "name": "ctime",
            "baseName": "ctime",
            "type": "number"
        },
        {
            "name": "mtime",
            "baseName": "mtime",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return BlockConfig.attributeTypeMap;
    }
}

