/**
 * BlockData API
 * BlockData API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { Building } from './building';

export class BuildingPage {
    /**
    * 翻页数据
    */
    'content'?: Array<Building>;
    /**
    * 总数量
    */
    'total'?: number;
    /**
    * 页码
    */
    'pageNo'?: number;
    /**
    * 翻页大小
    */
    'pageSize'?: number;
    /**
    * 翻页数量
    */
    'pageCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "Array<Building>"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number"
        },
        {
            "name": "pageNo",
            "baseName": "pageNo",
            "type": "number"
        },
        {
            "name": "pageSize",
            "baseName": "pageSize",
            "type": "number"
        },
        {
            "name": "pageCount",
            "baseName": "pageCount",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return BuildingPage.attributeTypeMap;
    }
}

