/**
 * BlockData API
 * BlockData API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class CategoryResource {
    /**
    * id
    */
    'id'?: string;
    /**
    * 应用ID
    */
    'appId'?: string;
    /**
    * 分类Id
    */
    'categoryId'?: string;
    /**
    * 资源Id
    */
    'resourceId'?: string;
    /**
    * 创建时间
    */
    'ctime'?: number;
    /**
    * 更改时间
    */
    'mtime'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "appId",
            "baseName": "appId",
            "type": "string"
        },
        {
            "name": "categoryId",
            "baseName": "categoryId",
            "type": "string"
        },
        {
            "name": "resourceId",
            "baseName": "resourceId",
            "type": "string"
        },
        {
            "name": "ctime",
            "baseName": "ctime",
            "type": "number"
        },
        {
            "name": "mtime",
            "baseName": "mtime",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CategoryResource.attributeTypeMap;
    }
}

